	    /****************************************************************
		** Class: AIPlayer.java                                        **
		** Author: Jimmy                                               **
		** Date: 18 Nov 2012                                           **
		** Description: This class is the supper class for the random  **
		** and systematic AI.  It processes the shots generated by     **
		** the two AIs.                                                **
		*****************************************************************/

/**
 * This class tracks prior shots taken by the AI, and requests shots
 * based on the AI's style
 */
public class AIPlayer {
	
	protected int[][] shotsFired;
	
	/**
	 * stub method overridden by the children
	 * @return
	 */
	public int[][] fireShot() {
		return null;
	}
	
	/**
	 * Determines of the next shot has already been taken
	 * @param row
	 * @param column
	 * @return true if already taken
	 */
	protected boolean hasShot(int row, int column){
		
		boolean hasShot = false;
		
		if(shotsFired != null){
			for(int i = 0; i<shotsFired.length;i++){

				if(shotsFired[i][0] == column && shotsFired[i][1] == row){
					hasShot = true;
				}
			}
		}
		return hasShot;
	}
	
	/**
	 * Adds a successful shot (hit or miss) to the array of shots taken
	 * @param column
	 * @param row
	 */
	protected void addShotFired(int column, int row){
		
		if(shotsFired == null){//add first shot
			
			shotsFired =  new int[1][2];
			
			shotsFired[0][0]= column;
			shotsFired[0][1]= row;
		}else{
			
			int[][] tempShots = new int[shotsFired.length][2];
			
			for(int i = 0;i<shotsFired.length;i++){
				
				tempShots[i][0] = shotsFired[i][0];
				tempShots[i][1] = shotsFired[i][1];
			
			}
			
			shotsFired = new int[shotsFired.length+1][2];
			
			for(int i = 0; i<tempShots.length;i++){
				
				shotsFired[i][0] = tempShots[i][0];
				shotsFired[i][1] = tempShots[i][1];

			}
			
			shotsFired[shotsFired.length-1][0] = column;
			shotsFired[shotsFired.length-1][1] = row;
			
		}
	}
}
		
	
